---
# Almost all linters; some of them are optional.

linters-settings:
  depguard:
    list-type: blacklist
    include-go-root: true
    rules:
      Main:
        files:
          - "$all"
          - "!$test"
        allow:
          - "$gostd"
          - "github.com/aws/aws-sdk-go"
          - "github.com/jinzhu/gorm"
          - "k8s.io/client-go/tools/clientcmd"
          - "github.com/AlekSi/pointer"
          - "k8s.io/client-go/rest"
          - "github.com/labstack/echo/v4"
          - "github.com/pkg/errors"
          - "github.com/golang-migrate/migrate"
          - "github.com/lib/pq"
          - "github.com/percona/percona-everest-backend"
          - "github.com/google/uuid"
          - "github.com/deepmap/oapi-codegen"
          - "github.com/kelseyhightower/envconfig"
      Tests:
        files:
          - "$test"
        allow:
          - "$gostd"
          - "github.com/stretchr/testify"
    packages:
      # use "github.com/pkg/errors" instead
      - errors
      # use "github.com/golang/protobuf/proto" instead
      - github.com/gogo/protobuf/proto

  goimports:
    local-prefixes: github.com/percona/percona-everest-backend

  unused:
    check-exported: true

  unparam:
    check-exported: true

  gci:
    sections:
      - standard # Captures all standard packages if they do not match another section.
      - default # Contains all imports that could not be matched to another section type.
      - prefix(github.com/percona/percona-everest-backend) # Groups all local imports.


linters:
  enable-all: true
  disable:
    - exhaustruct      # not useful
    - exhaustivestruct # annoying and duplicates exhaustruct
    - godox            # fails to be nolint-ed when necessary
    - gomnd            # not useful
    - lll              # generated signatures are long
    - maligned         # deprecated, replaced by fieldalignment. We're ok wasting a couple bytes now
    - nlreturn         # too many empty lines makes methods too long
    - varnamelen       # it's useful sometime to have a one-letter name
    - wrapcheck        # forces to wrap errors everywhere
    - wsl              # too many empty lines makes methods too long

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen       # tests may be long
        - testpackage  # senseless
