version: "3"
services:
  vault:
    image: vault
    environment:
      VAULT_ADDRESS: http://127.0.0.1:8200
      VAULT_TOKEN: root
    ports:
      - "8200:8200"
    volumes:
      - ./vault/config:/vault/config
      - ./vault/data:/vault/data
      - ./vault/logs:/vault/logs

