openapi: 3.0.2
servers:
  - url: /v1
info:
  version: 1.0.0
  title: Percona Everest schema
tags:
  - name: k8s
    description: Everything related to kubernetes clusters
  - name: db
    description: Everything related to database clusters
paths:
  /kubernetes:
    post:
      tags:
        - k8s
      summary: Register kubernetes cluster in Everest
      description: Register kubernetes cluster in Everest
      operationId: registerKubernetesCluster
      responses:
        '201':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KubernetesCluster'
        '400':
          description: Unsuccessful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      requestBody:
        description: The kubernetes cluster object to be created
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/KubernetesCluster'
    get:
      tags:
        - k8s
      summary: List of the registered kubernetes clusters
      description: List of the registered kubernetes clusters
      operationId: listKubernetesClusters
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KubernetesCluster'
        '400':
          description: Unsuccessful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/kubernetes/{kubernetesName}/databaseclusters':
    post:
      tags:
        - k8s
        - databaseCluster
      summary: Create a database cluster on the specified kubernetes cluster
      description: Create a database cluster on the specified kubernetes cluster
      operationId: createDatabaseCluster
      parameters:
        - name: kubernetesName
          in: path
          description: Name of the kubernetes cluster
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: './databasecluster.yml'
        '201':
          description: Created successfully
          content:
            application/json:
              schema:
                $ref: './databasecluster.yml'
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                $ref: './databasecluster.yml'
        '400':
          description: Unsuccessful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      requestBody:
        description: The database cluster object to be created
        required: true
        content:
          application/json:
            schema:
              $ref: './databasecluster.yml'
    get:
      tags:
        - k8s
        - databaseCluster
      summary: List of the created database clusters on the specified kubernetes cluster
      description: List of the created database clusters on the specified kubernetes cluster
      operationId: listDatabaseClusters
      parameters:
        - name: kubernetesName
          in: path
          description: Name of the kubernetes cluster
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DatabaseClusterList'
        '400':
          description: Unsuccessful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/kubernetes/{kubernetesName}/databaseclusters/{name}':
    get:
      tags:
        - k8s
        - databaseCluster
      summary: Get the specified database cluster on the specified kubernetes cluster
      description: Get the specified database cluster on the specified kubernetes cluster
      operationId: getDatabaseCluster
      parameters:
        - name: kubernetesName
          in: path
          description: Name of the kubernetes cluster
          required: true
          schema:
            type: string
        - name: name
          in: path
          description: Name of database cluster
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: './databasecluster.yml'
        '400':
          description: Unsuccessful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
        - k8s
        - databaseCluster
      summary: Replace the specified database cluster on the specified kubernetes cluster
      description: Replace the specified database cluster on the specified kubernetes cluster
      operationId: updateDatabaseCluster
      parameters:
        - name: kubernetesName
          in: path
          description: Name of the kubernetes cluster
          required: true
          schema:
            type: string
        - name: name
          in: path
          description: Name of database cluster
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: './databasecluster.yml'
        '400':
          description: Unsuccessful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      requestBody:
        description: The database cluster object to be updated
        required: true
        content:
          application/json:
            schema:
              $ref: './databasecluster.yml'
    delete:
      tags:
        - k8s
        - databaseCluster
      summary: Delete the specified database cluster on the specified kubernetes cluster
      description: Delete the specified database cluster on the specified kubernetes cluster
      operationId: deleteDatabaseCluster
      parameters:
        - name: kubernetesName
          in: path
          description: Name of the kubernetes cluster
          required: true
          schema:
            type: string
        - name: name
          in: path
          description: Name of database cluster
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: './databasecluster.yml'
        '400':
          description: Unsuccessful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/kubernetes/{kubernetesName}/databaseengines':
    get:
      tags:
        - k8s
        - databaseEngine
      summary: List of the available database engines on the specified kubernetes cluster
      description: List of available database engines on the specified kubernetes cluster
      operationId: listDatabaseEngines
      parameters:
        - name: kubernetesName
          in: path
          description: Name of the kubernetes cluster
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DatabaseEngineList'
        '400':
          description: Unsuccessful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/kubernetes/{kubernetesName}/databaseclusterrestores':
    post:
      tags:
        - k8s
        - databaseClusterRestore
      summary: Create a database cluster restore on the specified kubernetes cluster
      description: Create a database cluster restore on the specified kubernetes cluster
      operationId: createDatabaseClusterRestore
      parameters:
        - name: kubernetesName
          in: path
          description: Name of the kubernetes cluster
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: './databaseclusterrestore.yml'
        '201':
          description: Created success
          content:
            application/json:
              schema:
                $ref: './databaseclusterrestore.yml'
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                $ref: './databaseclusterrestore.yml'
        '400':
          description: Unsuccessful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      requestBody:
        description: The database cluster restore object to be created
        required: true
        content:
          application/json:
            schema:
              $ref: './databaseclusterrestore.yml'
    get:
      tags:
        - k8s
        - databaseClusterRestore
      summary: List of the created database cluster restores on the specified kubernetes cluster
      description: List of the created database cluster restores on the specified kubernetes cluster
      operationId: listDatabaseClusterRestores
      parameters:
        - name: kubernetesName
          in: path
          description: Name of the kubernetes cluster
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DatabaseClusterRestoreList'
        '400':
          description: Unsuccessful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/kubernetes/{kubernetesName}/databaseclusterrestores/{name}':
    get:
      tags:
        - k8s
        - databaseClusterRestore
      summary: Returns the specified cluster restore on the specified kubernetes cluster
      description: Returns the specified cluster restore on the specified kubernetes cluster
      operationId: getDatabaseClusterRestore
      parameters:
        - name: kubernetesName
          in: path
          description: Name of the kubernetes cluster
          required: true
          schema:
            type: string
        - name: name
          in: path
          description: Name of the database cluster restore
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: './databaseclusterrestore.yml'
        '400':
          description: Unsuccessful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
        - k8s
        - databaseClusterRestore
      summary: Replace the specified cluster restore on the specified kubernetes cluster
      description: Replace the specified cluster restore on the specified kubernetes cluster
      operationId: updateDatabaseClusterRestore
      parameters:
        - name: kubernetesName
          in: path
          description: Name of the kubernetes cluster
          required: true
          schema:
            type: string
        - name: name
          in: path
          description: Name of the database cluster restore
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: './databaseclusterrestore.yml'
        '201':
          description: Created successful
          content:
            application/json:
              schema:
                $ref: './databaseclusterrestore.yml'
        '400':
          description: Unsuccessful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      requestBody:
        description: The database cluster restore object to be updated
        required: true
        content:
          application/json:
            schema:
              $ref: './databaseclusterrestore.yml'
    delete:
      tags:
        - k8s
        - databaseClusterRestore
      summary: Delete the specified cluster restore on the specified kubernetes cluster
      description: Delete the specified cluster restore on the specified kubernetes cluster
      operationId: deleteDatabaseClusterRestore
      parameters:
        - name: kubernetesName
          in: path
          description: Name of the kubernetes cluster
          required: true
          schema:
            type: string
        - name: name
          in: path
          description: Name of the database cluster restore
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: './databaseclusterrestore.yml'
        '400':
          description: Unsuccessful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: object
      description: Error response
      properties:
        message:
          type: string
    KubernetesCluster:
      type: object
      description: kubernetes object
      properties:
        name:
          type: string
          example: minikube
        kubeconfig:
          type: string
    KubernetesClusterList:
      type: array
      items:
        type: object
        $ref: '#/components/schemas/KubernetesCluster'
    DatabaseClusterList:
      type: array
      items:
        type: object
        $ref: './databasecluster.yml'
    DatabaseEngineList:
      type: array
      items:
        type: object
        $ref: './databaseengine.yml'
    DatabaseClusterRestoreList:
      type: array
      items:
        type: object
        $ref: './databaseclusterrestore.yml'
    SizeLimit:
      anyOf:
        - $ref: '#/components/schemas/Integer'
        - $ref: '#/components/schemas/String'
      description: 'sizeLimit is the total amount of local storage required for this EmptyDir volume. The size limit is also applicable for memory medium. The maximum usage on memory medium EmptyDir would be the minimum value between the SizeLimit specified here and the sum of memory limits of all containers in a pod. The default is nil which means that the limit is undefined. More info: http://kubernetes.io/docs/user-guide/volumes#emptydir'
      pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
      x-kubernetes-int-or-string: true
    Integer:
      type: integer
    String:
      type: string
