name: Build and push RC image

on:
  workflow_dispatch:
    inputs:
      version:
        description: A release version in v*.*.* format
        required: true
  push:
    branches:
      - release-[0-9]+.[0-9]+.[0-9]+*
      - rc-test # <-- DELETE ME
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      #VERSION: ${{ github.event.inputs.version }}
      VERSION: v100.100.100
      RC_BRANCH: ''
    steps:
      - name: Validate input
        run: |
          echo $RC_BRANCH
          if [[ ! $VERSION =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Wrong version format provided, please use v*.*.* format" 
            exit 1
          fi
      - name: Define release branch name in the format "release-*.*.*"
        run: |
          echo "RC_BRANCH=release-${VERSION#v}" >> $GITHUB_ENV

      - name: Configure git for private modules
        env:
          ROBOT_TOKEN: ${{ secrets.ROBOT_TOKEN }}
        run: git config --global url."https://percona-platform-robot:${ROBOT_TOKEN}@github.com".insteadOf "https://github.com"

#      - name: Check out frontend repo
#        uses: actions/checkout@v4
#        with:
#          repository: percona/percona-everest-frontend
#          ref: 'main'
#          path: percona-everest-frontend
#          token: ${{ secrets.ROBOT_TOKEN }}
#          run: |
#            cd percona-everest-frontend
#
#            # Check if the branch already exists
#            if ! git rev-parse --verify --quiet "refs/heads/$RC_BRANCH"; then
#              git checkout -b $RC_BRANCH origin/main
#            else
#              git checkout $RC_BRANCH
#            fi

#      - name: Run with Node 16
#        uses: actions/setup-node@v3
#        with:
#          node-version: ${{ matrix.node-version }}
#
#      - name: Install Bit Version Manager
#        run: npm i -g @teambit/bvm
#
#      - name: Install latest Bit version
#        run: bvm install 0.2.3
#
#      - name: Add bvm bin folder to path
#        run: echo "$HOME/bin" >> $GITHUB_PATH
#
#      - name: Set up bit config
#        env:
#          BIT_TOKEN: ${{ secrets.BIT_TOKEN }}
#        run: bit config set user.token $BIT_TOKEN
#
#      - name: Build Everest Frontend app
#        run: |
#          cd ${GITHUB_WORKSPACE}/percona-everest-frontend
#          bit install --recurring-install
#          bit snap
#          bit artifacts percona.apps/everest --out-dir build
#          mkdir ${GITHUB_WORKSPACE}/front
#          cp -rf build/percona.apps_everest/react-common-js/everest/public/* ${GITHUB_WORKSPACE}/front/
#

      - name: Check out Everest Backend
        uses: actions/checkout@v4
        with:
          path: ./backend
          ref: 'main'
      - name: Check out Everest Backend
        run: |
          cd backend
          # Check if the branch already exists
          if ! git rev-parse --verify --quiet "refs/heads/$RC_BRANCH"; then
            git checkout -b $RC_BRANCH
            git push origin $RC_BRANCH
          else
            git checkout $RC_BRANCH
          fi
#
#      - name: Embed Everest Frontend app into backend
#        run: |
#          cp -rf ${GITHUB_WORKSPACE}/front/* ${GITHUB_WORKSPACE}/backend/public/dist/
#          cd ${GITHUB_WORKSPACE}/backend
#
#      - name: Set tag from inputs
#        run: echo "IMAGE_TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
#        if: ${{ github.event.inputs.tag != '' }}
#
#      - name: Set tag from inputs
#        run: echo "IMAGE_TAG=dev-latest" >> $GITHUB_ENV
#        if: ${{ github.event.inputs.tag == '' }}
#
#      - name: Setup docker build metadata
#        uses: docker/metadata-action@v4
#        id: meta
#        with:
#          images: perconalab/everest
#          tags: ${{ env.IMAGE_TAG }}
#
#
#      - name: Login to GitHub Container Registry
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      - name: Build and Push everest dev-latest image
#        uses: docker/build-push-action@v4
#        with:
#          context: backend
#          push: true
#          tags: ${{ steps.meta.outputs.tags }}
