name: Build and push RC image

on:
  workflow_dispatch:
    inputs:
      version:
        description: A release version in vX.Y.Z format
        required: true
  push:
    branches:
      - release-[0-9]+.[0-9]+.[0-9]+*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Configure git for private modules
        env:
          ROBOT_TOKEN: ${{ secrets.ROBOT_TOKEN }}
        run: git config --global url."https://percona-platform-robot:${ROBOT_TOKEN}@github.com".insteadOf "https://github.com"
